const DEFAULT_POINTS = [
  { x: 220, y: 220 },
  { x: 560, y: 220 },
  { x: 560, y: 560 },
  { x: 220, y: 560 }
];
export const TabsData = [
  {
    label: 'Google Layout',
    points: DEFAULT_POINTS,
    centroid: null,
    setCentroid: null,
    snapToCentroid: false,
    setSnapToCentroid: null,
    inputDegree: 0,
    setInputDegree: null,
    translate:{ x: 0, y: 0 },
    setTranslate:null,
    zoom:1,
    setZoom:1
  },
  {
    label: 'House Plan',
    points: DEFAULT_POINTS,
    centroid: null,
    setCentroid: null,
    snapToCentroid: false,
    setSnapToCentroid: null,
    inputDegree: 0,
    setInputDegree: null,
    translate:{ x: 0, y: 0 },
    setTranslate:null,
    zoom:1,
    setZoom:1
  },
  {
    label: 'Griding With 16 Zone',
    points: DEFAULT_POINTS,
    centroid: null,
    setCentroid: null,
    snapToCentroid: false,
    setSnapToCentroid: null,
    inputDegree: 0,
    setInputDegree: null,
    translate:{ x: 0, y: 0 },
    setTranslate:null,
    zoom:1,
    setZoom:1
  },
  {
    label: '16 Zone Bar Chart',
    points: DEFAULT_POINTS,
    centroid: null,
    setCentroid: null,
    snapToCentroid: false,
    setSnapToCentroid: null,
    inputDegree: 0,
    setInputDegree: null,
    translate:{ x: 0, y: 0 },
    setTranslate:null,
    zoom:1,
    setZoom:1
  },
  {
    label: 'Civil Energy',
    points: DEFAULT_POINTS,
    centroid: null,
    setCentroid: null,
    snapToCentroid: false,
    setSnapToCentroid: null,
    inputDegree: 0,
    setInputDegree: null,
    translate:{ x: 0, y: 0 },
    setTranslate:null,
    zoom:1,
    setZoom:1
  },
  {
    label: 'Devta Mark',
    points: DEFAULT_POINTS,
    centroid: null,
    setCentroid: null,
    snapToCentroid: false,
    setSnapToCentroid: null,
    inputDegree: 0,
    setInputDegree: null,
    translate:{ x: 0, y: 0 },
    setTranslate:null,
    zoom:1,
    setZoom:1
  },
  {
    label: 'Devta Marking Color',
    points: DEFAULT_POINTS,
    centroid: null,
    setCentroid: null,
    snapToCentroid: false,
    setSnapToCentroid: null,
    inputDegree: 0,
    setInputDegree: null,
    translate:{ x: 0, y: 0 },
    setTranslate:null,
    zoom:1,
    setZoom:1
  },
  {
    label: 'Devta bar chart',
    points: DEFAULT_POINTS,
    centroid: null,
    setCentroid: null,
    snapToCentroid: false,
    setSnapToCentroid: null,
    inputDegree: 0,
    setInputDegree: null,
    translate:{ x: 0, y: 0 },
    setTranslate:null,
    zoom:1,
    setZoom:1
  },
  {
    label: 'Devta + Marma Points',
    points: DEFAULT_POINTS,
    centroid: null,
    setCentroid: null,
    snapToCentroid: false,
    setSnapToCentroid: null,
    inputDegree: 0,
    setInputDegree: null,
    translate:{ x: 0, y: 0 },
    setTranslate:null,
    zoom:1,
    setZoom:1
  },
  {
    label: 'Custom Remedial Marking',
    points: DEFAULT_POINTS,
    centroid: null,
    setCentroid: null,
    snapToCentroid: false,
    setSnapToCentroid: null,
    inputDegree: 0,
    setInputDegree: null,
    translate:{ x: 0, y: 0 },
    setTranslate:null,
    zoom:1,
    setZoom:1
  },
  {
    label: 'Site Energy audit',
    points: DEFAULT_POINTS,
    centroid: null,
    setCentroid: null,
    snapToCentroid: false,
    setSnapToCentroid: null,
    inputDegree: 0,
    setInputDegree: null,
    translate:{ x: 0, y: 0 },
    setTranslate:null,
    zoom:1,
    setZoom:1
  },
  {
    label: 'Geo ',
    points: DEFAULT_POINTS,
    centroid: null,
    setCentroid: null,
    snapToCentroid: false,
    setSnapToCentroid: null,
    inputDegree: 0,
    setInputDegree: null,
    translate:{ x: 0, y: 0 },
    setTranslate:null,
    zoom:1,
    setZoom:1
  }
]
