const DEFAULT_POINTS = [
  { x: 220, y: 220 },
  { x: 560, y: 220 },
  { x: 560, y: 560 },
  { x: 220, y: 560 }
];
const DEFAULT_TAB_CONFIG = {
  points: DEFAULT_POINTS,
  centroid: null,
  setCentroid: null,
  snapToCentroid: false,
  setSnapToCentroid: null,
  inputDegree: 0,
  setInputDegree: null,
  translate: { x: 0, y: 0 },
  setTranslate: null,
  zoom: 1,
  setZoom: null,
  polygons:[],
  setPolygons:null
};
// export const TabsData = [
//   {
//     label: 'Google Layout',
//     points: DEFAULT_POINTS,
//     centroid: null,
//     setCentroid: null,
//     snapToCentroid: false,
//     setSnapToCentroid: null,
//     inputDegree: 0,
//     setInputDegree: null,
//     translate:{ x: 0, y: 0 },
//     setTranslate:null,
//     zoom:1,
//     setZoom:1
//   },
//   {
//     label: 'House Plan',
//     points: DEFAULT_POINTS,
//     centroid: null,
//     setCentroid: null,
//     snapToCentroid: false,
//     setSnapToCentroid: null,
//     inputDegree: 0,
//     setInputDegree: null,
//     translate:{ x: 0, y: 0 },
//     setTranslate:null,
//     zoom:1,
//     setZoom:1
//   },
//   {
//     label: 'Griding With 16 Zone',
//     points: DEFAULT_POINTS,
//     centroid: null,
//     setCentroid: null,
//     snapToCentroid: false,
//     setSnapToCentroid: null,
//     inputDegree: 0,
//     setInputDegree: null,
//     translate:{ x: 0, y: 0 },
//     setTranslate:null,
//     zoom:1,
//     setZoom:1
//   },
//   {
//     label: '16 Zone Bar Chart',
//     points: DEFAULT_POINTS,
//     centroid: null,
//     setCentroid: null,
//     snapToCentroid: false,
//     setSnapToCentroid: null,
//     inputDegree: 0,
//     setInputDegree: null,
//     translate:{ x: 0, y: 0 },
//     setTranslate:null,
//     zoom:1,
//     setZoom:1
//   },
//   {
//     label: 'Civil Energy',
//     points: DEFAULT_POINTS,
//     centroid: null,
//     setCentroid: null,
//     snapToCentroid: false,
//     setSnapToCentroid: null,
//     inputDegree: 0,
//     setInputDegree: null,
//     translate:{ x: 0, y: 0 },
//     setTranslate:null,
//     zoom:1,
//     setZoom:1
//   },
//   {
//     label: 'Devta Mark',
//     points: DEFAULT_POINTS,
//     centroid: null,
//     setCentroid: null,
//     snapToCentroid: false,
//     setSnapToCentroid: null,
//     inputDegree: 0,
//     setInputDegree: null,
//     translate:{ x: 0, y: 0 },
//     setTranslate:null,
//     zoom:1,
//     setZoom:1
//   },
//   {
//     label: 'Devta Marking Color',
//     points: DEFAULT_POINTS,
//     centroid: null,
//     setCentroid: null,
//     snapToCentroid: false,
//     setSnapToCentroid: null,
//     inputDegree: 0,
//     setInputDegree: null,
//     translate:{ x: 0, y: 0 },
//     setTranslate:null,
//     zoom:1,
//     setZoom:1
//   },
//   {
//     label: 'Devta bar chart',
//     points: DEFAULT_POINTS,
//     centroid: null,
//     setCentroid: null,
//     snapToCentroid: false,
//     setSnapToCentroid: null,
//     inputDegree: 0,
//     setInputDegree: null,
//     translate:{ x: 0, y: 0 },
//     setTranslate:null,
//     zoom:1,
//     setZoom:1
//   },
//   {
//     label: 'Devta + Marma Points',
//     points: DEFAULT_POINTS,
//     centroid: null,
//     setCentroid: null,
//     snapToCentroid: false,
//     setSnapToCentroid: null,
//     inputDegree: 0,
//     setInputDegree: null,
//     translate:{ x: 0, y: 0 },
//     setTranslate:null,
//     zoom:1,
//     setZoom:1
//   },
//   {
//     label: 'Custom Remedial Marking',
//     points: DEFAULT_POINTS,
//     centroid: null,
//     setCentroid: null,
//     snapToCentroid: false,
//     setSnapToCentroid: null,
//     inputDegree: 0,
//     setInputDegree: null,
//     translate:{ x: 0, y: 0 },
//     setTranslate:null,
//     zoom:1,
//     setZoom:1
//   },
//   {
//     label: 'Site Energy audit',
//     points: DEFAULT_POINTS,
//     centroid: null,
//     setCentroid: null,
//     snapToCentroid: false,
//     setSnapToCentroid: null,
//     inputDegree: 0,
//     setInputDegree: null,
//     translate:{ x: 0, y: 0 },
//     setTranslate:null,
//     zoom:1,
//     setZoom:1
//   },
//   {
//     label: 'Geo ',
//     points: DEFAULT_POINTS,
//     centroid: null,
//     setCentroid: null,
//     snapToCentroid: false,
//     setSnapToCentroid: null,
//     inputDegree: 0,
//     setInputDegree: null,
//     translate:{ x: 0, y: 0 },
//     setTranslate:null,
//     zoom:1,
//     setZoom:1
//   }
// ]

const TAB_LABELS = [
  'Google Layout',
  'House Plan',
  'Griding With 16 Zone',
  '16 Zone Bar Chart',
  'Civil Energy',
  'Devta Mark',
  'Devta Marking Color',
  'Devta bar chart',
  'Devta + Marma Points',
  'Custom Remedial Marking',
  'Site Energy audit',
  'Geo ',
];

export const TabsData = TAB_LABELS.map(label => ({ label, ...DEFAULT_TAB_CONFIG }));

